# The below functions allow the user to cache the
# inverse of a matrix to evade repeating lenghty 
# calculations. The second one must be applied on
# the list generated by the first one

# The first function generates a list with four
# elements: i) a "set" function, which allows the user 
# to set the underlying matrix by; ii) a "get" 
# function, to retrieve the underlying matrix,
# iii) a setInverse function, to assign the calculated
# inverse to the cache, and iv) a getInverse function,
# to retrieve the cached inverse from the list.


makeCacheMatrix<-function(x=matrix()){
        m<-NULL
        set <- function(y){
                x<<-y
                m<<-NULL
        }
        get <- function() x
        setInverse <- function(inverse) m <<- inverse
        getInverse <- function() m
        list(set = set,get = get,
             setInverse = setInverse,
             getInverse = getInverse)
}

# The second function works directly on the list
# generated by the first function and retrieves from
# its contents either the matrix whose inverse needs
# to be calculated or, if it has already been done,
# the cached inverse matrix stored in it.

cacheSolve <- function(x,...){
        m <- x$getInverse()
        if(!is.null(m)){
                message("Inverse has been retrieved
                        from cache data")
                return(m)
        }
        data <- x$get()
        m <- solve(data)
        x$setInverse(m)
        m
}